create table reader (
                        id int8 generated by default as identity primary key ,
                        f_name varchar not null ,
                        email varchar not null unique
);

create table author (
                        id int8 generated by default as identity primary key ,
                        f_name varchar not null ,
                        email varchar not null unique
);

create table book (
                      id int8 generated by default as identity primary key ,
                      name varchar not null ,
                      year timestamp not null ,
                      id_author int8 references author(id) on DELETE cascade ,
                      id_reader int8 references reader(id) on delete set null
);

create table deal (
                      book_id int8 not null ,
                      reader_id int8 not null ,
                      get_on timestamp not null ,
                      give_on timestamp not null
);
